# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.03
    steps:
      - checkout
      # Whatever you want to do
      - run: sudo apt-get update
      - run: sudo git clone https://github.com/Milzerk/estudo-sites-glass.git
